---
dist: focal
language: generic
sudo: required

services:
  - docker
  
  stages:
  - x86 build
  - ppc64le build
  - s390x build 
  - Multi arch build (ppc64le, s390x)


matrix:
  fast_finish: true
  include:

     - name: "Multi arch build using Python 3.7 on linux amd64 (x86_64) Intel, 64-bit, Little-endian"
       os: linux
       arch: amd64
       language: python
       python: 3.7
       compiler:
       - gcc
       - clang
       before_install:
       - hostnamectl
       - python --version
       - docker --version
       install: skip
       before_script: skip
       script: python hello.py
       env:
        - LIB_PATH="/usr/bin/shared/x86_64/v1"
       stage: x86 build

     - name: "IBM multi arch build using Python 3.7 on Linux ppc64le"
       os: linux
       dist: bionic
       arch: ppc64le 
       language: python
       python: 3.7
       before_install:
       - hostnamectl
       - python --version
       - docker --version
       install: skip
       before_script: skip
       script: python hello.py
       env:
        - LIB_PATH="/usr/bin/shared/x86_64/v1"
       stage: ppc64le build 

     - name: "IBM multi arch build using Python 3.7 on Linux s390x"
       os: linux
       dist: bionic
       arch: s390x
       language: python
       python: 3.7
       before_install:
       - hostnamectl
       - python --version
       - docker --version
       install: skip
       before_script: skip
       script: python hello.py
       env:
       - LIB_PATH="/usr/bin/shared/x86_64/v1"
       stage: s390x build 
       
     - name: "IBM multi arch build using Python 3.7 on Linux s390x and Linux ppc64le"
     
       os: linux
       dist: bionic
       arch: 
       - s390x
       - ppc64le  
       language: python
       python: 3.7
       before_install:
       - hostnamectl
       - python --version
       - docker --version
       install: skip
       before_script: skip
       script: python hello.py
       env:
       - LIB_PATH="/usr/bin/shared/x86_64/v1"
       stage: Multi arch build (ppc64le, s390x)
       
